---
- name: Install rustup
  become: true
  become_user: root
  pacman:
    name:
      - rustup

- name: Ensure directory exists
  file:
    path: /home/{{ user.name }}/.rustup
    state: directory
    recurse: yes

- name: Install chosen toolchain
  command: rustup toolchain install "{{ rust_toolchain_type }}"
  when: rust_install_toolchain

- name: Install rls
  command: rustup component add rls --toolchain "{{ rust_toolchain_type }}"
  when: rust_install_toolchain and rust_install_rls
