---
- name: Install fish
  become: true
  become_user: root
  pacman:
    name:
      - fish

- name: Ensure directory exists
  file:
    path: /home/{{ user.name }}/.config/fish
    state: directory
    recurse: yes

- name: Copy fish config
  template:
      src: config.fish
      dest: /home/{{ user.name }}/.config/fish

- name: Copy fish colors
  template:
      src: fish_variables
      dest: /home/{{ user.name }}/.config/fish/fish_variables

- name: Ensure directory exists
  file:
    path: /home/{{ user.name }}/.config/fish/functions
    state: directory
    recurse: yes

- name: Copy fundle setup script
  template:
      src: fundle.fish
      dest: /home/{{ user.name }}/.config/fish/functions

- name: Get plugins
  shell: fish -c "fundle install" && fish -c "fundle update"

- name: Enable shell
  become: true
  become_user: root
  user:
    name: "{{ user.name }}"
    shell: '{{ user.shell | default("/bin/bash") }}'
    state: present
