---
- name: Ensure builds/st folder exists
  file:
    path: /home/aur_builder/builds/st
    state: directory
    recurse: yes

- name: Copy config
  copy:
    src: config.h
    dest: /home/aur_builder/builds/st

- name: Copy PKGBUILD
  copy:
    src: PKGBUILD
    dest: /home/aur_builder/builds/st

- name: Build and install
  command: chdir=/home/aur_builder/builds/st makepkg -si --noconfirm
