---
- name: Install application for editing text
  pacman:
    name:
      - gvim
      - vim
      - neovim
      - emacs
      - vim-spell-en
      - vim-spell-pl
      - vim-spell-de


- name: Ensure directory exists
  file:
    path: /home/{{ user.name }}
    state: directory
    recurse: yes

- name: Copy vim config
  copy:
    src: vimrc
    dest: /home/{{ user.name }}/.vimrc
  register: result

- name: Ensure directory exists
  file:
    path: /home/{{ user.name }}/.config/nvim
    state: directory
    recurse: yes

- name: Copy neovim config
  copy:
    src: vimrc
    dest: /home/{{ user.name }}/.config/nvim/init.vim
  register: result

- name: Ensure directory exists
  file:
    path: /home/{{ user.name }}
    state: directory
    recurse: yes

- name: Copy YCM config
  copy:
      src: ycm_extra_conf.py
      dest: /home/{{ user.name }}/.ycm_extra_conf.py

- name: Copy tern config
  copy:
      src: tern-config
      dest: /home/{{ user.name }}/tern-config

- name: Set up Vundle
  git:
    dest: /home/{{ user.name }}/.vim/bundle/Vundle.vim
    repo: https://github.com/gmarik/Vundle.vim.git

- name: Download plugins if something changed
  # TODO: non zero return code, strange behaviour
  command: vim -E -c "PluginInstall" -c "q" -c "q"
  when: result.changed
  ignore_errors: true

- name: Check if YCM already compiled
  stat:
    path: /home/{{ user.name }}/.vim/bundle/YouCompleteMe/compiled
  register: result

- name: Compile YouCompleteMe
  command: chdir=/home/{{ user.name }}/.vim/bundle/YouCompleteMe ./install.py --clang-completer --go-completer --rust-completer --java-completer --system-libclang
  when: not result.stat.exists

- name: Set YCM as compiled
  lineinfile:
    path: /home/{{ user.name }}/.vim/bundle/YouCompleteMe/compiled
    line: 'true'
    create: yes
  when: not result.stat.exists

- name: Install binaries for vim-go
  # TODO: non zero return code, strange behaviour
  command: vim -E -c "GoInstallBinaries" -c "q"
  ignore_errors: true

- name: Copy emacs config
  copy:
    src: emacs
    dest: /home/{{ user.name }}/.emacs
