---
# Install applications
- hosts: all
  become: true
  roles:
      - { role: create_user }
      - { role: sudo }

      - { role: aur_builder }
      - { role: yay }

      - { role: browsers }
      - { role: cli }
      - { role: gui }
      - { role: editors }
      - { role: image }
      - { role: misc }
      - { role: necessary }
      - { role: network }
      - { role: office }
      - { role: programming }
      - { role: steam }
      - { role: video }
      - { role: vm }
      - { role: vpn }
      - { role: wine }
