---
# Install applications
- hosts: all
  become: true
  roles:

      - { role: create_user }
      - { role: sudo }

      - { role: aur_builder }
      - { role: yay }

      - { role: aur_voice }
      - { role: aur_browsers }
      - { role: aur_video }
      - { role: aur_spotify }
      - { role: aur_misc }
      - { role: aur_gui }

      - { role: gui }
      - { role: cli }
      - { role: utils }
      - { role: editors }
      - { role: browsers }
      - { role: editors }
      - { role: image }
      - { role: misc }
      - { role: necessary }
      - { role: network }
      - { role: office }
      - { role: programming }
      - { role: steam }
      - { role: video }
      - { role: vm }
      - { role: vpn }
      - { role: wine }
      - { role: python_packages }
      - { role: js_packages }
      - { role: go_packages }
