---
# Install applications
- hosts: all
  become: true
  become_user: root
  roles:
      - { role: pacman }

      - { role: create_user }
      - { role: networkmanager }

      - { role: sudo, tags: install }

      - { role: aur_builder }
      - { role: yay }

      - { role: aur_voice }
      - { role: aur_browsers }
      - { role: aur_video }
      - { role: aur_spotify }
      - { role: aur_misc }
      - { role: aur_gui }
        #- { role: aur_ide }

      - { role: gui }
      - { role: cli }
      - { role: utils }
      - { role: editors }
      - { role: browsers }
      - { role: editors }
      - { role: image }
      - { role: misc }
      - { role: necessary }
      - { role: network }
      - { role: office }
      - { role: programming }
      - { role: steam }
      - { role: video }
      - { role: vm }
      - { role: vpn }
      - { role: wine }
      - { role: python_packages }
      - { role: nvidia, when: pc == "g751" }
      - { role: js_packages }
      - { role: go_packages }
  tags:
      - install

# Set up
- hosts: all
  become: true
  become_user: "{{ user.name }}"
  roles:
    - { role: sudo, tags: configure }
    - { role: i3 }
    - { role: ssh }
    - { role: tmux }
    - { role: git }
    - { role: zsh }
    - { role: ranger }
    - { role: vim }
    - { role: compton }
    - { role: dunst }
    - { role: rofi }
    - { role: xresources }
    - { role: qutebrowser }
    - { role: emacs }
  tags:
      - configure
