---
- name: Set up  virtualization stuff
  pacman:
    name:
      - qemu
      - qemu-arch-extra 
      - docker

- name: Started docker
  systemd:
      state: started
      name: docker

- name: Enabled docker
  systemd:
      enabled: yes
      name: docker

- name: Add user to docker group
  user:
    name: "{{ user.name }}"
    groups: docker
    state: present
    append: true
