---
- name: Ensure directory exists
  file:
    path: /home/{{ user.name }}
    state: directory
    recurse: yes

- name: Copy Xresources dotfile
  copy:
      src: Xresources
      dest: /home/{{ user.name }}/.Xresources
