---
- name: Install qutebrowser
  become: true
  become_user: root
  pacman:
    name:
      - qutebrowser

- name: Ensure directory exists
  file:
    path: /home/{{ user.name }}/.config/qutebrowser
    state: directory
    recurse: yes

- name: Copy qutebrowser config
  copy:
      src: qute_config.py
      dest: /home/{{ user.name }}/.config/qutebrowser/config.py

- name: Ensure scripts directory exists
  file:
    path: /home/{{ user.name }}/.config/qutebrowser/scripts
    state: directory
    recurse: yes

- name: Copy download script
  copy:
      src: download_video.sh
      dest: /home/{{ user.name }}/.config/qutebrowser/scripts/download_video.sh

# TODO: move to separate bitwarden rol
- name: Install password manager and dependency
  pacman:
    name:
    - python-tldextract
