---
- name: Ensure directory exists
  file:
    path: /home/{{ user.name }}/.config/qutebrowser
    state: directory
    recurse: yes

- name: Copy qutebrowser config
  copy:
      src: qute_config.py
      dest: /home/{{ user.name }}/.config/qutebrowser/config.py
