---
- name: Install some needed utilities
  pacman:
    name:
      - fuse
      - pacman-contrib
      - udiskie
      - ntfs-3g
      - zsh
      - keychain
      - exfat-utils

- name: Copy zsh config
  copy:
      src: zshrc
      dest: /home/{{ user.name }}/.zshrc

# TODO: oh my zsh
