---
- name: Install compton
  become: true
  become_user: root
  pacman:
    name:
      - compton

- name: Ensure directory exists
  file:
    path: /home/{{ user.name }}/.config
    state: directory
    recurse: yes

- name: Copy compton dotfile
  copy:
      src: compton.conf
      dest: /home/{{ user.name }}/.config/compton.conf
