---
- name: Install compton and transset-df
  become: true
  become_user: root
  pacman:
    name:
      - compton
      - transset-df

- name: Ensure directory exists
  become: true
  become_user: "{{ user.name }}"
  file:
    path: /home/{{ user.name }}/.config
    state: directory
    recurse: yes

- name: Copy compton dotfile
  become: true
  become_user: "{{ user.name }}"
  copy:
      src: compton.conf
      dest: /home/{{ user.name }}/.config/compton.conf
