---
- name: Set up X
  become: true
  become_user: root
  pacman:
    name: 
      - xorg
      - xorg-xinit 
      - i3
      - awesome-terminal-fonts
      - dunst
      - scrot 
      - flameshot
      - rofi 
      - ponymix 
      - playerctl 
      - feh
      - redshift 
      - compton 
      - transset-df
      - ttf-hack
      - rxvt-unicode
      - kitty
      - terminator
      - mesa-demos
      - ttf-inconsolata
      - powerline
      - powerline-fonts

- name: Set up audio
  become: true
  become_user: root
  pacman:
    name:
      - alsa-utils
      - pulseaudio
      - pulseaudio-bluetooth
      - pulseaudio-equalizer
      - pulseaudio-jack
      - pavucontrol
