---
- name: Update repos
  pacman:
    update_cache: yes

- name: Upgrade
  pacman:
    upgrade: yes

- name: Set up X
  pacman:
    name: 
      - xorg
      - xorg-xinit 
      - i3
      - dunst
      - scrot 
      - rofi 
      - ponymix 
      - playerctl 
      - feh
      - redshift 
      - compton 
      - transset-df
      - ttf-hack
      - rxvt-unicode
      - terminator
      - mesa-demos
      - ttf-inconsolata

- name: Ensure directory exists
  file:
    path: /home/{{ user.name }}/.config
    state: directory
    recurse: yes

- name: Copy compton dotfile
  copy:
      src: compton.conf
      dest: /home/{{ user.name }}/.config/compton.conf

- name: Ensure directory exists
  file:
    path: /home/{{ user.name }}/.config/dunst
    state: directory
    recurse: yes

- name: Copy dunst dotfile
  copy:
      src: dunstrc
      dest: /home/{{ user.name }}/.config/dunst/dunstrc

- name: Ensure directory exists
  file:
    path: /home/{{ user.name }}/.config/rofi
    state: directory
    recurse: yes

- name: Copy rofi dotfile
  copy:
      src: rofi_config
      dest: /home/{{ user.name }}/.config/rofi/config

- name: Ensure directory exists
  file:
    path: /home/{{ user.name }}
    state: directory
    recurse: yes

- name: Copy Xresources dotfile
  copy:
      src: Xresources
      dest: /home/{{ user.name }}/.Xresources


- name: Set up audio
  pacman:
    name:
      - alsa-utils
      - pulseaudio
      - pulseaudio-bluetooth
      - pulseaudio-equalizer
      - pulseaudio-jack
      - pavucontrol
