---
- name: Install openssh
  become: true
  become_user: root
  pacman:
    name:
      - openssh

- name: Ensure directory exists
  become: true
  become_user: "{{ user.name }}"
  file:
    path: /home/{{ user.name }}/.ssh
    state: directory
    recurse: yes

- name: Copy ssh config
  become: true
  become_user: "{{ user.name }}"
  copy:
      src: ssh_config
      dest: /home/{{ user.name }}/.ssh/config

- name: Start sshd
  become: true
  become_user: root
  systemd:
      name: sshd
      state: started
      enabled: true
  when: pc == "g751"
