---
- name: Ensure directory exists
  file:
    path: /home/{{ user.name }}/.config/ranger
    state: directory
    recurse: yes

- name: Copy ranger config
  copy:
      src: rc.conf
      dest: /home/{{ user.name }}/.config/ranger/rc.conf
