---
# Get zsh install script, and modify it for automation.

- name: Ensure directory exists
  file:
    path: /home/{{ user.name }}/.oh-my-zsh/themes
    state: directory
    recurse: yes

- name: Copy theme
  copy:
    src: tosAgnoster.zsh-theme
    dest: /home/{{ user.name }}/.oh-my-zsh/themes/tosAgnoster.zsh-theme

- name: Install zsh and suggestions
  become: true
  become_user: root
  pacman:
    name:
      - zsh
      - zsh-autosuggestions

- name: Download zsh script
  get_url:
    url: https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh
    dest: /tmp/ohmyzsh.sh

- name: Get zsh
  command: chdir=/tmp {{ item }}
  with_items:
      - sed -i.tmp 's:env zsh -l::g' ohmyzsh.sh
      - sh ohmyzsh.sh

- name: Copy zsh config
  template:
      src: zshrc
      dest: /home/{{ user.name }}/.zshrc

- name: Enable shell
  become: true
  become_user: root
  user:
    name: "{{ user.name }}"
    shell: '{{ user.shell | default("/bin/bash") }}'
    state: present
