---
# Get zsh install script, and modify it for automation.

- name: Download zsh script
  get_url:
    url: https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh
    dest: /tmp/ohmyzsh.sh

- name: Get zsh
  command: chdir=/tmp {{ item }}
  with_items:
      - sed -i.tmp 's:env zsh -l::g' ohmyzsh.sh
      - sh ohmyzsh.sh

- name: Copy zsh config
  copy:
      src: zshrc
      dest: /home/{{ user.name }}/.zshrc

- name: Enable shell
  become: true
  become_user: root
  user:
    name: "{{ user.name }}"
    shell: '{{ user.shell | default("/bin/bash") }}'
    state: present
