---
- name: Ensure directory exists
  file:
    path: /home/{{ user.name }}/.config/i3/config_temp
    state: directory
    recurse: yes

- name: Copy scripts directory
  synchronize:
    src: scripts
    dest: /home/{{ user.name }}/.config/i3/scripts
  delegate_to: "{{ inventory_hostname }}"

- name: Copy base config
  copy:
    src: base
    dest: /home/{{ user.name }}/.config/i3/config_temp/base
  register: base_res

- name: Copy specific config
  copy:
    src: specific_{{ pc }}
    dest: /home/{{ user.name }}/.config/i3/config_temp/specific
  register: spec_res

- name: Merge configs
  assemble:
      src: /home/{{ user.name }}/.config/i3/config_temp
      dest: /home/{{ user.name }}/.config/i3/config
      delimiter: "#################################################################"

- name: Copy specific status config
  copy:
    src: specific_status_{{ pc }}
    dest: /home/{{ user.name }}/.config/i3/i3status.conf

- name: Copy specific xinitrc
  copy:
    src: specific_xinitrc_{{ pc }}
    dest: /home/{{ user.name }}/.xinitrc
