---
- name: Install scrot
  pacman:
    name: scrot
    state: present

- name: Install i3lock-fancy
  aur:
    use: yay
    name: i3lock-fancy-git
  become: yes
  become_user: aur_builder

- name: Copy suspend service file
  copy:
    src: suspend@.service
    dest: /etc/systemd/system/

- name: Copy resume service file
  copy:
    src: resume@.service
    dest: /etc/systemd/system/

- name: Enable suspend service file
  systemd:
      name: suspend@{{ user.name }}
      enabled: true

- name: Enable resume service file
  systemd:
      name: resume@{{ user.name }}
      enabled: true
