---
- name: Ensure directory exists
  file:
    path: /home/{{ user.name }}/.config/dunst
    state: directory
    recurse: yes

- name: Copy dunst dotfile
  copy:
      src: dunstrc
      dest: /home/{{ user.name }}/.config/dunst/dunstrc
