---
- name: Install contrib
  become: true
  become_user: root
  pacman:
    name:
      - pacman-contrib

- name: enable colors
  lineinfile:
    dest: /etc/pacman.conf
    state: "present"
    regexp: "^Color"
    insertafter: "^#Color"
    line: "Color"

- name: multilib support 1
  lineinfile:
    dest: /etc/pacman.conf
    state: "present"
    line: "[multilib]"
    regexp: "^\\[multilib\\]"
    insertafter: "^#\\[multilib\\]"

- name: multilib 2
  lineinfile:
    dest: /etc/pacman.conf
    state: "present"
    line: "Include = /etc/pacman.d/mirrorlist"
    insertafter: "^\\[multilib\\]"
    regexp: "Include = /etc/pacman.d/mirrorlist"

- name: Update repos
  become: true
  become_user: root
  pacman:
    update_cache: yes
  when: pacman_update

- name: Upgrade packages
  become: true
  become_user: root
  pacman:
    upgrade: yes
  when: pacman_upgrade
