---
- name: Ensure directory exists
  file:
    path: /home/{{ user.name }}/.config/rofi
    state: directory
    recurse: yes

- name: Copy rofi dotfile
  copy:
      src: rofi_config
      dest: /home/{{ user.name }}/.config/rofi/config
