---
- name: Ensure directory exists
  file:
    path: /home/{{ user.name }}/.tmux/plugin
    state: directory
    recurse: yes

- name: Clone tmux plugin manager
  git:
    repo: https://github.com/tmux-plugins/tpm.git
    dest: /home/{{ user.name }}/.tmux/plugins/tpm

- name: Ensure directory exists
  file:
    path: /home/{{ user.name }}
    state: directory
    recurse: yes

- name: Copy tmux.conf
  copy:
    src: tmux.conf
    dest: /home/{{ user.name }}/.tmux.conf
