---
- name: Ensure directory exists
  file:
    path: /home/{{ user.name }}/.gnupg
    state: directory
    recurse: yes

- name: Copy gpg config
  copy:
      src: gpg_config
      dest: /home/{{ user.name }}/.gnupg/gpg-agent.conf
