---
- name: Install GPG
  become: true
  become_user: root
  pacman:
    name:
      - gnupg

- name: Ensure directory exists
  file:
    path: /home/{{ user.name }}/.gnupg
    state: directory
    recurse: yes

- name: Copy gpg config
  copy:
      src: gpg_config
      dest: /home/{{ user.name }}/.gnupg/gpg-agent.conf

- name: Set gpg key to use with git
  git_config:
    name: user.signingkey
    scope: global
    value: "{{ user.gpg_key }}"
  when: user.gpg_key is defined

- name: Set git to always use gpg
  git_config:
    name: commit.gpgsign
    scope: global
    value: "true"
  when: user.always_git_gpg is defined
