---
- name: Install NetworkManager
  pacman:
    name: networkmanager
    state: present 

- name: Start and enable NM
  systemd:
      name: NetworkManager
      enabled: yes
      state: started

- name: Install NetworkManager's applet
  pacman:
    name: network-manager-applet
    state: present
  when: network_manager_enable_gui
